import Logo from "@/components/nav/Logo";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: `%s | Ted's Reminder`,
    default: `Ted's Reminder`,
  },
  description: "Reminder dashboard generated by NextJs",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-full">
      <div className="flex justify-between items-center p-10">
        <Logo />
      </div>

      {children}
    </main>
  );
}
