import Logo from "@/components/nav/Logo";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: `%s | Ted's Reminder`,
    default: `Ted's Reminder`,
  },
  description: "Reminder dashboard generated by NextJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-full">
          <div className="flex justify-between items-center p-10">
            <Logo />
          </div>

          {children}
        </main>
      </body>
    </html>
  );
}
