import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import SnackProvider from "@/hook/toast/SnackbarProvider";
import CustomTheme from "@/theme/ThemeProvider";
import { useContext } from "react";

import MainLoader from "@/components/loader/MainLoader";
import AuthProvider from "@/middleware/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: `%s | Ted's Reminder`,
    default: `Ted's Reminder`,
  },
  description: "Reminder dashboard generated by NextJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <StoreProvider>
          <CustomTheme>
            <SnackProvider>{children}</SnackProvider>
          </CustomTheme>
        </StoreProvider>
      </body>
    </html>
  );
}
