import Logo from "@/components/nav/Logo";
import NavBar from "@/components/nav/NavBar";
import SideBar from "@/components/nav/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: `%s | Ted's Reminder`,
    default: `Ted's Reminder`,
  },
  description: "Reminder dashboard generated by NextJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          style={{ height: "100vh", width: "100vw" }}
          className="flex gap-3 pr-3"
        >
          <SideBar />
          <div className="flex flex-col flex-1">
            <NavBar />
            <div className="p-3">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
